Remove dev.Dockerfiles, add better staged build in backend

diff --git a/helloworldredux/backend/Dockerfile b/helloworldredux/backend/Dockerfile
--- a/helloworldredux/backend/Dockerfile
+++ b/helloworldredux/backend/Dockerfile
@@ -1,30 +1,39 @@
-# Build and run a back-end service with a SpringBoot app based on
-# https://github.com/spring-guides/gs-spring-boot-docker
-#
-# This is what you would want to run for a clean build and deployment. If you're
-# looking for running a quicker version based on your local environment, build
-# with `dev.Dockerfile`
+# Multi-stage build image for Spring Boot applications.
 
 ### BUILD STEP ###
-FROM gradle:jdk8 as builder
+FROM openjdk:8-slim as builder
+ENV APP_HOME=/usr/app
 
-COPY --chown=gradle:gradle . /home/gradle/src
-WORKDIR /home/gradle/src
-RUN ./gradlew bootJar
+# This is a trick from Sairam Krish on Stack Overflow. If we just build the
+# gradle file, we have to redownload all the dependencies when a single file
+# changes. We don't care about rebuilding those dependencies every single time
+# unless we add or change one. So if we run it now, it will fail, but all the
+# dependencies will be there. We stop everything from failing by `return`ing 0
+# to force a success. Any format failures in the build file will be caught when
+# we pull the rest of the source code.
+#
+# https://stackoverflow.com/questions/25873971/docker-cache-gradle-dependencies
+WORKDIR $APP_HOME
+COPY build.gradle settings.gradle gradlew $APP_HOME/
+COPY gradle $APP_HOME/gradle
+RUN ./gradlew --no-daemon build || return 0
 
+# Now copy everything else and build it as a separte step.
+COPY . .
+RUN ./gradlew --no-daemon build
 
 ### RUN STEP ###
 FROM openjdk:8-slim
+ENV APP_HOME=/usr/app
 
 # By default, Docker runs apps as a root user in the container. We'll create a
 # separate one just for the app.
 RUN addgroup --system spring && adduser --system spring --ingroup spring
 USER spring:spring
-WORKDIR /home/spring
+WORKDIR $APP_HOME
 
 # Copy all the JAR file over
-ARG JAR_FILE=build/libs/*.jar
-COPY --from=builder --chown=spring:spring /home/gradle/src/${JAR_FILE} app.jar
+COPY --from=builder --chown=spring:spring $APP_HOME/build/libs/*.jar app.jar
 
 # Start the main class on container start.
 ENTRYPOINT ["java","-jar","app.jar"]
